name = "GadgetIO"
uuid = "826b50da-1eb7-48f3-bd4b-d2350582c309"
authors = ["LudwigBoess <lboess@usm.lmu.de>"]
version = "0.8.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Dates = "1"
DelimitedFiles = "1"
Downloads = "1"
LinearAlgebra = "1"
PrecompileTools = "1"
Printf = "1"
ProgressMeter = "1.3"
Statistics = "1"
julia = "1.7"
